/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.94
 * Generated at: 2024-11-07 13:19:18 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class ownWeb_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<title>Easy Market - Online Shopping</title>\r\n");
      out.write(" <link rel=\"stylesheet\" href=\"styles.css\">\r\n");
      out.write("<style>\r\n");
      out.write("body, h1, h2, p {\r\n");
      out.write("    margin: 0;\r\n");
      out.write("    padding: 0;\r\n");
      out.write("}\r\n");
      out.write("body {\r\n");
      out.write("    background-color: #f2f2f2;\r\n");
      out.write("    font-family: Arial, sans-serif;\r\n");
      out.write("}\r\n");
      out.write("    header {\r\n");
      out.write("    background-color: #ff6600; /* Change this color to your desired header background color */\r\n");
      out.write("    box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);\r\n");
      out.write("    \r\n");
      out.write("    nav {\r\n");
      out.write("    display: flex;\r\n");
      out.write("    justify-content: space-between;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("    padding: 10px 20px;\r\n");
      out.write("}\r\n");
      out.write("nav ul {\r\n");
      out.write("	\r\n");
      out.write("    list-style: none;\r\n");
      out.write("    display: flex;\r\n");
      out.write("}\r\n");
      out.write("nav li {\r\n");
      out.write("    margin-right: 20px;\r\n");
      out.write("}\r\n");
      out.write(".hero {\r\n");
      out.write("    background-color: #fff;\r\n");
      out.write("    padding: 40px;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("}\r\n");
      out.write(".hero h1 {\r\n");
      out.write("    font-size: 36px;\r\n");
      out.write("    margin-bottom: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".hero p {\r\n");
      out.write("    font-size: 18px;\r\n");
      out.write("    color: #777;\r\n");
      out.write("    margin-bottom: 20px;\r\n");
      out.write("}\r\n");
      out.write("footer {\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    background-color: #ff6600;\r\n");
      out.write("    color: #fff;\r\n");
      out.write("    padding: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write(" <header>\r\n");
      out.write("        <nav>\r\n");
      out.write("            <ul>\r\n");
      out.write("                <li><a href=\"#products\">Clothes and Fashion</a></li>\r\n");
      out.write("                <li><a href=\"#categories\">Groceries</a></li>\r\n");
      out.write("                <li><a href=\"#deals\">Gold</a></li>\r\n");
      out.write("                <li><a href=\"#cart\">Electronics Shopping Cart</a></li>\r\n");
      out.write("                <li><a href=\"#cart\">Sports</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </nav>\r\n");
      out.write("    </header>\r\n");
      out.write("      <section class=\"hero\">\r\n");
      out.write("        <div class=\"hero-content\">\r\n");
      out.write("            <h1>Welcome to Easy Market</h1>\r\n");
      out.write("            <p>Your One-Stop Online Shopping Destination</p>\r\n");
      out.write("            <a href=\"#products\" class=\"cta-button\">Shop Now</a>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("    </section>\r\n");
      out.write("    <hr>\r\n");
      out.write("    <h2 style=\"text-align: center;\">Clothes and Fashion</h2>\r\n");
      out.write("    <div class=\"product-container\">\r\n");
      out.write("    <section id=\"products\" class=\"products\" style=\"display: flex;\">\r\n");
      out.write("    \r\n");
      out.write("    <div class=\"product-card highlights\">\r\n");
      out.write("			    <img src=\"Cami-Top.jpg\" alt=\"Sample Image\" width=\"300\" height=\"200\">\r\n");
      out.write("			    <h3>Cami Top Dress</h3>\r\n");
      out.write("			    <p>Product Description 1</p>\r\n");
      out.write("			    <span class=\"price\">$3,949.99</span>\r\n");
      out.write("			    <a href=\"class=\"add-to-cart\">Buy Now</a>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"product-card highlights\">\r\n");
      out.write("			    <img src=\"Cotton-Shirts.jpg\" alt=\"Sample Image\" width=\"300\" height=\"200\">\r\n");
      out.write("			    <h3>Cotton Gents Shirts</h3>\r\n");
      out.write("			    <p>Product Description 1</p>\r\n");
      out.write("			    <span class=\"price\">$4,099.99</span>\r\n");
      out.write("			    <a href=\"http://localhost/php-practice/praveen/site/flipkart_form.php\" class=\"add-to-cart\">Buy Now</a>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"product-card highlights\">\r\n");
      out.write("			    <img src=\"women dress.jpg\" alt=\"Sample Image\" width=\"300\" height=\"200\">\r\n");
      out.write("			    <h3>Asymmetrical Top</h3>\r\n");
      out.write("			    <p>Product Description 1</p>\r\n");
      out.write("			    <span class=\"price\">$2,349.99</span>\r\n");
      out.write("			    <a href=\"http://localhost/php-practice/praveen/site/amazon_form.php\" class=\"add-to-cart\">Buy Now</a>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"product-card highlights\">\r\n");
      out.write("			    <img src=\"Shirt.jpg\" alt=\"Product 1\" width=\"300\" height=\"200\">\r\n");
      out.write("			    <h3>Casual Gents Shirts</h3>\r\n");
      out.write("			    <p>Product Description 1</p>\r\n");
      out.write("			    <span class=\"price\">$2,449.99</span>\r\n");
      out.write("			    <a href=\"http://localhost/php-practice/praveen/site/amazon_form.php\" class=\"add-to-cart\">Buy Now</a>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"product-card highlights\">\r\n");
      out.write("			    <img src=\"WhatsApp Image 2023-10-12 at 12.32.29_75f8371e.jpg\" alt=\"Product 1\" width=\"300\" height=\"200\">\r\n");
      out.write("			    <h3>Emprire Top</h3>\r\n");
      out.write("			    <p>Product Description 1</p>\r\n");
      out.write("			    <span class=\"price\">$2,999.99</span>\r\n");
      out.write("			    <a href=\"http://localhost/php-practice/praveen/site/amazon_form.php\" class=\"add-to-cart\">Buy Now</a>\r\n");
      out.write("			</div>\r\n");
      out.write("			</section>\r\n");
      out.write("    </div>\r\n");
      out.write("    <hr>\r\n");
      out.write("    <h2 style=\"text-align: center;\">Groceries</h2>\r\n");
      out.write("    <div class=\"product-container\">\r\n");
      out.write("    <section id=\"categories\" class=\"categories\" style=\"display: flex;\">\r\n");
      out.write("    <div class=\"product-card highlights\">\r\n");
      out.write("			    <img src=\"WhatsApp Image 2023-10-12 at 12.20.49_4b5a0d76.jpg\" alt=\"Product 1\" width=\"300\" height=\"200\">\r\n");
      out.write("			    <h3>Devaaya Basmati Rice</h3>\r\n");
      out.write("			    <p>Product Description 1</p>\r\n");
      out.write("			    <span class=\"price\">$1549.99</span>\r\n");
      out.write("			    <a href=\"http://localhost/php-practice/praveen/site/flipkart_form.php\" class=\"add-to-cart\">Buy Now</a>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"product-card highlights\">\r\n");
      out.write("			    <img src=\"WhatsApp Image 2023-10-12 at 12.20.49_08043506.jpg\" alt=\"Product 1\" width=\"300\" height=\"200\">\r\n");
      out.write("			    <h3>Daawat Devaaya Basmati Rice</h3>\r\n");
      out.write("			    <p>Product Description 1</p>\r\n");
      out.write("			    <span class=\"price\">$1449.99</span>\r\n");
      out.write("			    <a href=\"http://localhost/php-practice/praveen/site/amazon_form.php\" class=\"add-to-cart\">Buy Now</a>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"product-card highlights\">\r\n");
      out.write("			    <img src=\"WhatsApp Image 2023-10-12 at 12.20.50_84bd821d.jpg\" alt=\"Product 1\" width=\"300\" height=\"200\">\r\n");
      out.write("			    <h3>Sun Flower Oil</h3>\r\n");
      out.write("			    <p>Product Description 1</p>\r\n");
      out.write("			    <span class=\"price\">$149.99</span>\r\n");
      out.write("			    <a href=\"http://localhost/php-practice/praveen/site/amazon_form.php\" class=\"add-to-cart\">Buy Now</a>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"product-card highlights\">\r\n");
      out.write("			    <img src=\"WhatsApp Image 2023-10-12 at 12.20.50_c18f54da.jpg\" alt=\"Product 1\" width=\"300\" height=\"200\">\r\n");
      out.write("			    <h3>Ghee</h3>\r\n");
      out.write("			    <p>Product Description 1</p>\r\n");
      out.write("			    <span class=\"price\">$83.99</span>\r\n");
      out.write("			    <a href=\"http://localhost/php-practice/praveen/site/amazon_form.php\" class=\"add-to-cart\">Buy Now</a>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"product-card highlights\">\r\n");
      out.write("			    <img src=\"WhatsApp Image 2023-10-12 at 12.20.51_60fa72fc.jpg\" alt=\"Product 1\" width=\"300\" height=\"200\" >\r\n");
      out.write("			    <h3>Chick pea</h3>\r\n");
      out.write("			    <p>Product Description 1</p>\r\n");
      out.write("			    <span class=\"price\">$499.99</span>\r\n");
      out.write("			    <a href=\"http://localhost/php-practice/praveen/site/flipkart_form.php\" class=\"add-to-cart\">Buy Now</a>\r\n");
      out.write("			</div>\r\n");
      out.write("			</section>\r\n");
      out.write("			</div>\r\n");
      out.write("			<h2 style=\"text-align: center;\">Gold</h2>\r\n");
      out.write("    <div class=\"product-container\">\r\n");
      out.write("    <section id=\"deals\" class=\"categories\" style=\"display: flex;\">  \r\n");
      out.write("        <!-- Within the products or categories section, add product cards -->\r\n");
      out.write("			<div class=\"product-card highlights\">\r\n");
      out.write("			    <img src=\"71y+f6r75tL._AC_SS260_.jpg\" alt=\"Product 1\" width=\"300\" height=\"200\">\r\n");
      out.write("			    <h3>Watches Sonata</h3>\r\n");
      out.write("			    <p>Product Description 1</p>\r\n");
      out.write("			    <span class=\"price\">$1,33,49.9</span>\r\n");
      out.write("			    <a href=\"http://localhost/php-practice/praveen/site/amazon_form.php\" class=\"add-to-cart\">Buy Now</a>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"product-card highlights\">\r\n");
      out.write("			    <img src=\"71OKNZr3SmL._AC_SS260_.jpg\" alt=\"Product 1\" width=\"300\" height=\"200\">\r\n");
      out.write("			    <h3>Watches Gold</h3>\r\n");
      out.write("			    <p>Product Description 1</p>\r\n");
      out.write("			    <span class=\"price\">$1,49,343.9</span>\r\n");
      out.write("			    <a href=\"http://localhost/php-practice/praveen/site/flipkart_form.php\" class=\"add-to-cart\">Buy Now</a>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"product-card highlights\">\r\n");
      out.write("			    <img src=\"71TI3XtIIPL._AC_SS260_.jpg\" alt=\"Product 1\" width=\"300\" height=\"200\">\r\n");
      out.write("			    <h3>Gold Chain Necklace</h3>\r\n");
      out.write("			    <p>Product Description 1</p>\r\n");
      out.write("			    <span class=\"price\">$3,34,449.9</span>\r\n");
      out.write("			    <a href=\"http://localhost/php-practice/praveen/site/flipkart_form.php\" class=\"add-to-cart\">Buy Now</a>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"product-card highlights\">\r\n");
      out.write("			    <img src=\"71A1uqwKSdL._AC_SS260_.jpg\" alt=\"Product 1\" width=\"300\" height=\"200\">\r\n");
      out.write("			    <h3>Gold Stone Necklace</h3>\r\n");
      out.write("			    <p>Product Description 1</p>\r\n");
      out.write("			    <span class=\"price\">$5,73,649.9</span>\r\n");
      out.write("			    <a href=\"http://localhost/php-practice/praveen/site/amazon_form.php\" class=\"add-to-cart\">Buy Now</a>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"product-card highlights\">\r\n");
      out.write("			    <img src=\"Bangle.jpg\" alt=\"Product 1\" width=\"300\" height=\"200\">\r\n");
      out.write("			    <h3>Gold Vaddanam</h3>\r\n");
      out.write("			    <p>Product Description 1</p>\r\n");
      out.write("			    <span class=\"price\">$9,49,673.9</span>\r\n");
      out.write("			    <a href=\"http://localhost/php-practice/praveen/site/flipkart_form.php\" class=\"add-to-cart\">Buy Now</a>\r\n");
      out.write("			</div>\r\n");
      out.write("    </section>\r\n");
      out.write("    </div>\r\n");
      out.write("    <hr>\r\n");
      out.write("    <h2 style=\"text-align: center;\">Electronics Shopping Cart</h2>\r\n");
      out.write("    <div class=\"product-container\">\r\n");
      out.write("    <section id=\"cart\" class=\"cart\" style=\"display: flex;\">\r\n");
      out.write("        <div class=\"product-card highlights\">\r\n");
      out.write("			    <img src=\"41tSQSq1xJL._AC_UF334,334_FMjpg_.jpg\" alt=\"Product 1\" width=\"300\" height=\"200\">\r\n");
      out.write("			    <h3>Realme Zarzo</h3>\r\n");
      out.write("			    <p>Product Description 1</p>\r\n");
      out.write("			    <span class=\"price\">$23,249.99</span>\r\n");
      out.write("			    <a href=\"http://localhost/php-practice/praveen/site/amazon_form.php\" class=\"add-to-cart\">Buy Now</a>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"product-card highlights\">\r\n");
      out.write("			    <img src=\"WhatsApp Image 2023-10-12 at 12.10.07_33d977fc.jpg\" alt=\"Product 1\" width=\"300\" height=\"200\">\r\n");
      out.write("			    <h3>One Pluse</h3>\r\n");
      out.write("			    <p>Product Description 1</p>\r\n");
      out.write("			    <span class=\"price\">$49,333.99</span>\r\n");
      out.write("			    <a href=\"http://localhost/php-practice/praveen/site/amazon_form.php\" class=\"add-to-cart\">Buy Now</a>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"product-card highlights\">\r\n");
      out.write("			    <img src=\"WhatsApp Image 2023-10-12 at 12.10.07_32b59303.jpg\" alt=\"Product 1\" width=\"300\" height=\"200\">\r\n");
      out.write("			    <h3>M34 5G</h3>\r\n");
      out.write("			    <p>Product Description 1</p>\r\n");
      out.write("			    <span class=\"price\">$32,349.99</span>\r\n");
      out.write("			    <a href=\"http://localhost/php-practice/praveen/site/amazon_form.php\" class=\"add-to-cart\">Buy Now</a>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"product-card highlights\">\r\n");
      out.write("			    <img src=\"WhatsApp Image 2023-10-12 at 12.10.08_5e0f1e7e.jpg\" alt=\"Product 1\" width=\"300\" height=\"200\">\r\n");
      out.write("			    <h3>HP VICTUS</h3>\r\n");
      out.write("			    <p>Product Description 1</p>\r\n");
      out.write("			    <span class=\"price\">$49,433.99</span>\r\n");
      out.write("			    <a href=\"http://localhost/php-practice/praveen/site/flipkart_form.php\" class=\"add-to-cart\">Buy Now</a>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"product-card highlights\">\r\n");
      out.write("			    <img src=\"WhatsApp Image 2023-10-12 at 12.10.08_a468dd33.jpg\" alt=\"Product 1\" width=\"300\" height=\"200\">\r\n");
      out.write("			    <h3>LG TV</h3>\r\n");
      out.write("			    <p>Product Description 1</p>\r\n");
      out.write("			    <span class=\"price\">$32,449.99</span>\r\n");
      out.write("			    <a href=\"http://localhost/php-practice/praveen/site/flipkart_form.php\" class=\"add-to-cart\">Buy Now</a>\r\n");
      out.write("			</div>\r\n");
      out.write("  \r\n");
      out.write("    </section>\r\n");
      out.write("	</div>\r\n");
      out.write("	<hr>\r\n");
      out.write("    <h2 style=\"text-align: center;\">Sports</h2>\r\n");
      out.write("    <div class=\"product-container\">\r\n");
      out.write("    <section id=\"products\" class=\"products\" style=\"display: flex;\">\r\n");
      out.write("            \r\n");
      out.write("       <!-- Within the products or categories section, add product cards -->\r\n");
      out.write("       		<div class=\"product-card highlights\">\r\n");
      out.write("			    <img src=\"Cricket.jpg\" alt=\"Product 1\" width=\"300\" height=\"200\">\r\n");
      out.write("			    <h3>Cricket Bat</h3>\r\n");
      out.write("			    <p>Product Description 1</p>\r\n");
      out.write("			    <span class=\"price\">$4,549.99</span>\r\n");
      out.write("			    <a href=\"http://localhost/php-practice/praveen/site/amazon_form.php\" class=\"add-to-cart\">Buy Now</a>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"product-card highlights\">\r\n");
      out.write("			    <img src=\"Vollyball.jpg\" alt=\"Product 1\" width=\"300\" height=\"200\">\r\n");
      out.write("			    <h3>Volleyball</h3>\r\n");
      out.write("			    <p>Product Description 1</p>\r\n");
      out.write("			    <span class=\"price\">$1,449.99</span>\r\n");
      out.write("			    <a href=\"http://localhost/php-practice/praveen/site/flipkart_form.php\" class=\"add-to-cart\">Buy Now</a>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"product-card highlights\">\r\n");
      out.write("			    <img src=\"6-9-high-quality-skating-in-line-shoe-have-different-size-and-original-imag9y7u6zgcehxz.jpeg.jpg\" alt=\"Product 1\" width=\"300\" height=\"200\">\r\n");
      out.write("			    <h3>Roller Skates Shoes</h3>\r\n");
      out.write("			    <p>Product Description 1</p>\r\n");
      out.write("			    <span class=\"price\">$2,349.99</span>\r\n");
      out.write("			    <a href=\"http://localhost/php-practice/praveen/site/flipkart_form.php\" class=\"add-to-cart\">Buy Now</a>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"product-card highlights\">\r\n");
      out.write("			    <img src=\"180-accessories-kit-wish-hunt-original-imagkwfvhptcy7w5.jpeg.jpg\" alt=\"Product 1\" width=\"300\" height=\"200\">\r\n");
      out.write("			    <h3>Fishing Hooks</h3>\r\n");
      out.write("			    <p>Product Description 1</p>\r\n");
      out.write("			    <span class=\"price\">$753.99</span>\r\n");
      out.write("			    <a href=\"http://localhost/php-practice/praveen/site/amazon_form.php\" class=\"add-to-cart\">Buy Now</a>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"product-card highlights\">\r\n");
      out.write("			    <img src=\"2-double-shaft-badminton-racquet-with-10-pc-nylon-shuttle-0100-original-imafx94uzjahcpqz.jpeg.jpg\" alt=\"Product 1\" width=\"300\" height=\"200\">\r\n");
      out.write("			    <h3>Shuttle bat</h3>\r\n");
      out.write("			    <p>Product Description 1</p>\r\n");
      out.write("			    <span class=\"price\">$449.99</span>\r\n");
      out.write("			    <a href=\"https://www.amazon.in/Hipkoo-Grab-Badminton-Set-Shuttlecocks/dp/B07D7Y7BHP/ref=sr_1_1_sspa?crid=2H9UM89SAATX5&keywords=shuttle+bats&qid=1697118911&sprefix=shuttle+batt%2Caps%2C284&sr=8-1-spons&sp_csd=d2lkZ2V0TmFtZT1zcF9hdGY&psc=1\" class=\"add-to-cart\">Buy Now</a>\r\n");
      out.write("			</div>\r\n");
      out.write("			\r\n");
      out.write("    </section>\r\n");
      out.write("    </div>\r\n");
      out.write("    <footer>\r\n");
      out.write("        <p>&copy; 2023 Easy Market. All rights reserved.</p>\r\n");
      out.write("    </footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
